import type { Achievement, FrameworkStep, ResearchDirection, TeamMember, TimelineNode } from './types'

export const SITE_CONFIG = {
  name: 'GreenAudit AI',
  fullName: '应对"新形态"洗绿行为：碳排放报告舞弊审计程序智能化重构研究',
  shortName: 'GreenAudit AI',
  description: 'AI驱动的碳排放舞弊审计研究 — 南京审计大学国家级大学生创新训练计划项目',
  school: '南京审计大学',
  url: 'https://greenaudit-ai.vercel.app',
  github: 'https://github.com/nau-esg/greenaudit-ai',
} as const

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'advisor-1',
    name: '屈耀辉',
    role: 'advisor',
    major: '会计学',
    grade: '指导教师',
    researchFocus: '项目总体指导、审计理论与方法研究',
    skills: ['会计学', '审计理论', '学术指导', '碳排放研究'],
    avatarUrl: '/images/team/屈耀辉.jpg',
    bio: '南京审计大学会计学教师，长期从事审计理论与实务研究，为本项目提供学术指导与方向把控。',
  },
  {
    id: 'student-1',
    name: '胡心怡',
    role: 'student',
    major: '审计学',
    grade: '2024级',
    researchFocus: '项目统筹管理、政策法规梳理与审计策略设计',
    skills: ['项目管理', '调研设计', '数据分析', '报告撰写', '审计策略'],
    avatarUrl: '/images/team/胡心怡.jpg',
    bio: '任班级班长，组织协调能力强。曾获"挑战杯"省赛参与、"正大杯"市场调查大赛校级特等奖、三创赛校级二等奖。负责整体进度管理、研究内容统稿及审计策略设计。',
  },
  {
    id: 'student-2',
    name: '陈亮宇',
    role: 'student',
    major: '审计学',
    grade: '2024级',
    researchFocus: '项目计划书撰写、材料美化与成果展示',
    skills: ['财务分析', '逻辑分析', '计划书撰写', '文案排版', '答辩展示'],
    avatarUrl: '/images/team/陈亮宇.jpg',
    bio: '任班级团支书，平均绩点4.06，专业排名前3%。曾获商业精英挑战赛校二等奖、简历大赛学院一等奖。负责项目计划书撰写与材料美化。',
  },
  {
    id: 'student-3',
    name: '靳舒',
    role: 'student',
    major: '计算机科学与技术',
    grade: '2024级',
    researchFocus: 'AI技术应用、数据清洗分析与风险建模',
    skills: ['Python', 'C语言', '数据清洗', '数据可视化', 'AI应用'],
    avatarUrl: '/images/team/靳舒.jpg',
    bio: '系统掌握C与Python编程，辅修会计学课程。具备从审计与风险控制视角审视数据处理流程的能力，能够识别数据异常及潜在舞弊风险。',
  },
  {
    id: 'student-4',
    name: '宋斯侬',
    role: 'student',
    major: '审计学',
    grade: '2024级',
    researchFocus: '文献综述、数据收集与整理',
    skills: ['文献检索', '资料整理', '数据分析', '审计思维', '碳数据研究'],
    avatarUrl: '/images/team/宋斯侬.jpg',
    bio: '担任班级学习委员，善于整合课程资源、组织学术讨论。具备文献检索、资料整理与基础数据分析能力，对财务数据敏感。负责文献综述与数据收集。',
  },
  {
    id: 'student-5',
    name: '秦雪',
    role: 'student',
    major: '审计学',
    grade: '2024级',
    researchFocus: '碳排放数据调研、舞弊行为识别与审计对策落地',
    skills: ['WPS全流程', '问卷设计', '数据整理', '报告撰写', '调研实施'],
    avatarUrl: '/images/team/秦雪.jpg',
    bio: '精通WPS全流程办公软件，选修《环境与健康》《问卷设计与数据分析实训》课程。具备极强的执行力与项目落地能力，负责碳排放数据调研与审计对策研究。',
  },
]

export const RESEARCH_DIRECTIONS: ResearchDirection[] = [
  {
    id: 'greenwashing-detection',
    icon: 'Search',
    title: '新形态洗绿行为识别',
    description: '运用自然语言处理与机器学习技术，识别企业碳排放报告中的新型洗绿行为模式，构建多维度特征识别体系。',
    keywords: ['洗绿识别', 'NLP', '文本分析', '模式识别'],
    color: '#00ff88',
  },
  {
    id: 'ai-audit-reconstruction',
    icon: 'Cpu',
    title: 'AI审计程序重构',
    description: '基于大语言模型与知识图谱，重构传统碳排放审计程序，实现审计流程的智能化与自动化升级。',
    keywords: ['审计重构', 'LLM', '知识图谱', '自动化'],
    color: '#00d4ff',
  },
  {
    id: 'esg-risk-analysis',
    icon: 'ShieldAlert',
    title: 'ESG风险分析',
    description: '构建多维度ESG风险评估模型，结合碳排放数据与财务指标，实现企业环境风险的精准量化分析。',
    keywords: ['ESG', '风险评估', '碳排放', '量化分析'],
    color: '#7c3aed',
  },
  {
    id: 'ai-anomaly-detection',
    icon: 'Activity',
    title: 'AI异常检测',
    description: '利用深度学习异常检测算法，对碳排放数据进行智能监控，实现舞弊信号的自动捕捉与预警。',
    keywords: ['异常检测', '深度学习', '预警系统', '数据监控'],
    color: '#f59e0b',
  },
]

export const FRAMEWORK_STEPS: FrameworkStep[] = [
  {
    step: 1,
    title: '传统舞弊分析',
    description: '梳理传统碳排放报告舞弊手法，建立舞弊特征库',
    icon: 'FileSearch',
    color: '#6366f1',
  },
  {
    step: 2,
    title: 'AI升级攻击识别',
    description: '分析AI时代新型洗绿攻击向量与规避技术',
    icon: 'Bot',
    color: '#8b5cf6',
  },
  {
    step: 3,
    title: '风险特征提取',
    description: '构建多维度风险指标体系与异常模式库',
    icon: 'Fingerprint',
    color: '#ec4899',
  },
  {
    step: 4,
    title: 'AI审计反制',
    description: '开发基于LLM的智能审计检测模型与反制策略',
    icon: 'Shield',
    color: '#00d4ff',
  },
  {
    step: 5,
    title: '审计流程重构',
    description: '完成碳排放审计程序的智能化重构与验证',
    icon: 'RefreshCw',
    color: '#00ff88',
  },
]

export const PROJECT_TIMELINE: TimelineNode[] = [
  {
    date: '2026.04',
    title: '项目启动',
    description: '完成团队组建、文献综述与研究方案设计',
    status: 'completed',
    icon: 'Rocket',
  },
  {
    date: '2026.08',
    title: '案例库建立',
    description: '收集企业碳排放报告数据，建立舞弊案例库',
    status: 'in-progress',
    icon: 'Database',
  },
  {
    date: '2026.10',
    title: '风险模型构建',
    description: '完成AI检测模型训练与风险评估体系搭建',
    status: 'upcoming',
    icon: 'Brain',
  },
  {
    date: '2027.01',
    title: '论文投稿',
    description: '完成研究论文撰写，投稿至核心期刊',
    status: 'upcoming',
    icon: 'FileText',
  },
  {
    date: '2027.04',
    title: '项目结项',
    description: '完成项目总结报告，通过结项答辩',
    status: 'upcoming',
    icon: 'Trophy',
  },
]

export const ACHIEVEMENTS: Achievement[] = [
  {
    slug: 'literature-review-2026',
    type: 'report',
    title: '碳排放报告舞弊审计文献综述',
    description: '系统梳理国内外碳排放舞弊审计研究现状，归纳传统舞弊手法与新型洗绿模式。',
    date: '2026-05',
    tags: ['文献综述', '舞弊审计', '碳排放'],
    featured: true,
  },
  {
    slug: 'case-library-v1',
    type: 'case',
    title: '碳排放舞弊案例库 V1.0',
    description: '收录50+家企业碳排放报告舞弊案例，包含行业分布、手法分类与特征标注。',
    date: '2026-08',
    tags: ['案例库', '数据分析', '特征标注'],
    featured: true,
  },
  {
    slug: 'ai-detection-model',
    type: 'data',
    title: 'AI洗绿检测模型训练报告',
    description: '基于BERT与图神经网络的洗绿行为检测模型训练与评估结果。',
    date: '2026-10',
    tags: ['AI模型', 'BERT', 'GNN', '模型评估'],
    featured: true,
  },
  {
    slug: 'midterm-ppt',
    type: 'ppt',
    title: '中期答辩PPT',
    description: '项目中期进展汇报，包含研究框架、阶段性成果与后续计划。',
    date: '2026-09',
    tags: ['答辩', 'PPT', '中期汇报'],
    featured: false,
  },
  {
    slug: 'paper-esg-risk',
    type: 'paper',
    title: 'AI驱动的ESG碳排放舞弊审计框架研究',
    description: '提出基于人工智能的碳排放舞弊审计新型框架，投稿至《审计研究》。',
    date: '2027-01',
    tags: ['论文', '审计框架', 'AI', 'ESG'],
    featured: true,
  },
  {
    slug: 'innovation-award',
    type: 'award',
    title: '国家级大创优秀项目',
    description: '获评南京审计大学大学生创新创业训练计划国家级优秀项目。',
    date: '2027-04',
    tags: ['获奖', '大创', '优秀项目'],
    featured: true,
  },
]

export const NAV_LINKS = [
  { label: '首页', href: '/' },
  { label: '研究方向', href: '/research' },
  { label: '团队成员', href: '/team' },
  { label: '研究成果', href: '/achievements' },
  { label: 'AI Lab', href: '/ai-lab' },
] as const
